[build]
  command = "npm install && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = '''
      default-src 'self';
      connect-src 'self' https://*.supabase.co https://*.huggingface.co https://api-inference.huggingface.co https://unpkg.com;
      style-src 'self' 'unsafe-inline' https://unpkg.com;
      script-src 'self' 'unsafe-inline' 'unsafe-eval' https://unpkg.com;
      img-src 'self' data: https: blob:;
      font-src 'self' data:;
      frame-src 'self';
      media-src 'self' blob:;
      worker-src 'self' blob:;
    '''
